### PR TITLE
Overcoat only requires PMKPromise, not all of PMK

### PR DESCRIPTION
**Pull request by mxcl**
Should you ever need more of PromiseKit it’s easy to add more subspecs.

### CODE REVIEW

**Comment by sodastsai** [comment]
@mxcl thanks! :+1:

**Comment by numerics** [comment]
When I was using Overcoat 2.1.1, cocoa pods installed PromiseKit 1.5.3... from your spec. Now it seems to be going backwards that Overcoat 3.0 uses PromiseKit 1.2...? Also, the Latest PromiseKit is 2.1.. is that suppose to be in Overcoat 3, (just transposed the numbers)?

**Comment by sodastsai** [comment]
Hi @numerics, the version specified in the `Podspec` is `~> 1.2` which means you could install any version which is equal to or greater than 1.2 but smaller than 2.0. _(>=1.2 and <2.0)_. So it's okay to keep using `1.5.3`.

I don't really use PromiseKit, but I could still try to adopt the Overcoat to compatible with the newest PromiseKit. You're welcome to submit a PR for this too. :smile:

**Comment by mxcl** [comment]
I could submit a PR to upgrade to 2.x, it probably is minimal.

**Pull request merged**
