### PR TITLE
Added Swift3 support for installing via Carthage

### PR DESCRIPTION
**Pull request by Iyuna**

### CODE REVIEW

**Comment by grgcombs** [comment]
Travis errors out when installing Cocoapods. Looks like a suitable Ruby isn't installed with the newer OS X images?

------------

Fetching: activesupport-5.0.0.rc2.gem (100%)
ERROR:  Error installing cocoapods:
	activesupport requires Ruby version >= 2.2.2.
The command "gem install cocoapods --pre" failed and exited with 1 during .

Your build has been stopped.

**Comment by Iyuna** [comment]
@grgcombs Yeah, thanks for your comments. Will try to fix.

**Comment by grgcombs** [comment]
Almost there --- Cocopods installed but is failing to execute your pod file, maybe due to a dependency issue

-------------

None of your spec sources contain a spec satisfying the dependencies: `OHHTTPStubs, OHHTTPStubs (= 4.7.1)`.

**Comment by grgcombs** [comment]
Ah you already saw that :-)

**Comment by Iyuna** [comment]
@grgcombs Yep, don't worry, I'm following the build details :).

**Comment by grgcombs** [comment]
Try adding "pod repo update" ?

**Comment by grgcombs** [comment]
Aw jeez. The pod update repo advice was a bad idea :-( 

Who'd have guessed that would blow up Travis-CI's logging capacity and turn a 2 minute build into 45 mins (before it was killed by Travis)

**Comment by grgcombs** [comment]
What really needs OHHTTPStubs?  Since it seems to be the root of all the Travis pain, can we live without it? Can we live with a prior, known working version?

**Comment by Iyuna** [comment]
Woohoo!! I was able to build this!!!

**Comment by Iyuna** [comment]
@grgcombs Better not merge it but make a separate branch so you can support earlier versions of Swift as well.

**Comment by grgcombs** [comment]
@Iyuna :
> Better not merge it but make a separate branch so you can support earlier versions of Swift as well.

Good idea -- I've created a new branch with your changes: [feature/Swift3](https://github.com/Overcoat/Overcoat/tree/feature/Swift3) -- d5802a323dfc9ac65f157f91d7101abebb407a38

**Pull request closed without merging**
