### PR TITLE
Improved Carthage support

### PR DESCRIPTION
**Pull request by alokard**
I've update `Carthfile` with same dependencies as for cocoapods. And also I have to disable bitcode  for iOS targets cause of Mantle framework. For now Mantle framework doesn't support bitcode code and we can't use bitcode without its support in our dependencies.

### CODE REVIEW

**Comment by Iyuna** [comment]
Guys, please, review this PR and merge it ASAP. Because right now because of `github "mxcl/PromiseKit" >= 2.0` Carthage automatically installs PromiseKit version 4.0.0 that is supported only by beta XCode 8.0.

**Comment by grgcombs** [comment]
Can you fix up the Travis-CI build errors?

**Comment by grgcombs** [comment]
Is the issue resolved or this pull-req obsoleted by the new feature/Swift3 branch? (btw, thanks @Iyuna !)

**Comment by Iyuna** [comment]
Implemented the same changes inside [pull request](https://github.com/Overcoat/Overcoat/pull/147).

**Comment by grgcombs** [comment]
Fixed up in #147

**Pull request closed without merging**
